production:
  auto_create: true
  deny_delete: false
  allow_add_local: true
  svn:
    path:     /opt/bitnami/repos/svn
    svnadmin: /opt/bitnami/subversion/bin/svnadmin
    url: svn
  git:
    path: /opt/bitnami/repos/git
    git:  /opt/bitnami/git/bin/git
    options: --bare
    url: git

